package com.chixing.mapper;

import com.chixing.pojo.ComBuyers;
import com.chixing.pojo.ComBuyersExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ComBuyersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int countByExample(ComBuyersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int deleteByExample(ComBuyersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int deleteByPrimaryKey(Integer comId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int insert(ComBuyers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int insertSelective(ComBuyers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    List<ComBuyers> selectByExample(ComBuyersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    ComBuyers selectByPrimaryKey(Integer comId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") ComBuyers record, @Param("example") ComBuyersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByExample(@Param("record") ComBuyers record, @Param("example") ComBuyersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByPrimaryKeySelective(ComBuyers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByPrimaryKey(ComBuyers record);
}