package com.chixing.mapper;

import com.chixing.pojo.MyOrder;
import com.chixing.pojo.MyOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MyOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int countByExample(MyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int deleteByExample(MyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int insert(MyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int insertSelective(MyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    List<MyOrder> selectByExample(MyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    MyOrder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") MyOrder record, @Param("example") MyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByExample(@Param("record") MyOrder record, @Param("example") MyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByPrimaryKeySelective(MyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_order
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByPrimaryKey(MyOrder record);
}