package com.chixing.mapper;

import com.chixing.pojo.TicketsPicture;
import com.chixing.pojo.TicketsPictureExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TicketsPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int countByExample(TicketsPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int deleteByExample(TicketsPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int deleteByPrimaryKey(Integer pictureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int insert(TicketsPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int insertSelective(TicketsPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    List<TicketsPicture> selectByExample(TicketsPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    TicketsPicture selectByPrimaryKey(Integer pictureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") TicketsPicture record, @Param("example") TicketsPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByExample(@Param("record") TicketsPicture record, @Param("example") TicketsPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByPrimaryKeySelective(TicketsPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    int updateByPrimaryKey(TicketsPicture record);
}