package com.chixing.pojo;

import java.io.Serializable;

public class ComBuyers implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_buyers.com_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_buyers.com_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String comName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_buyers.com_coi
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Long comCoi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_buyers.com_telno
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Long comTelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_buyers.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_buyers.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_buyers.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_buyers.com_id
     *
     * @return the value of com_buyers.com_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_buyers.com_id
     *
     * @param comId the value for com_buyers.com_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_buyers.com_name
     *
     * @return the value of com_buyers.com_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_buyers.com_name
     *
     * @param comName the value for com_buyers.com_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setComName(String comName) {
        this.comName = comName == null ? null : comName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_buyers.com_coi
     *
     * @return the value of com_buyers.com_coi
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Long getComCoi() {
        return comCoi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_buyers.com_coi
     *
     * @param comCoi the value for com_buyers.com_coi
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setComCoi(Long comCoi) {
        this.comCoi = comCoi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_buyers.com_telno
     *
     * @return the value of com_buyers.com_telno
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Long getComTelno() {
        return comTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_buyers.com_telno
     *
     * @param comTelno the value for com_buyers.com_telno
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setComTelno(Long comTelno) {
        this.comTelno = comTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_buyers.status
     *
     * @return the value of com_buyers.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_buyers.status
     *
     * @param status the value for com_buyers.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_buyers.other1
     *
     * @return the value of com_buyers.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_buyers.other1
     *
     * @param other1 the value for com_buyers.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_buyers.other2
     *
     * @return the value of com_buyers.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_buyers.other2
     *
     * @param other2 the value for com_buyers.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_buyers
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", comId=").append(comId);
        sb.append(", comName=").append(comName);
        sb.append(", comCoi=").append(comCoi);
        sb.append(", comTelno=").append(comTelno);
        sb.append(", status=").append(status);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}