package com.chixing.pojo;

import java.io.Serializable;

public class Host implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer hostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.host_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String hostName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.phone_number
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Long phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.link_man
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String linkMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.others1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String others1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table host
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_id
     *
     * @return the value of host.host_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_id
     *
     * @param hostId the value for host.host_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setHostId(Integer hostId) {
        this.hostId = hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.host_name
     *
     * @return the value of host.host_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.host_name
     *
     * @param hostName the value for host.host_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.phone_number
     *
     * @return the value of host.phone_number
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Long getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.phone_number
     *
     * @param phoneNumber the value for host.phone_number
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.link_man
     *
     * @return the value of host.link_man
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.link_man
     *
     * @param linkMan the value for host.link_man
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.status
     *
     * @return the value of host.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.status
     *
     * @param status the value for host.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.others1
     *
     * @return the value of host.others1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOthers1() {
        return others1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.others1
     *
     * @param others1 the value for host.others1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOthers1(String others1) {
        this.others1 = others1 == null ? null : others1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.other2
     *
     * @return the value of host.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.other2
     *
     * @param other2 the value for host.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host.other3
     *
     * @return the value of host.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther3() {
        return other3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host.other3
     *
     * @param other3 the value for host.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther3(String other3) {
        this.other3 = other3 == null ? null : other3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hostId=").append(hostId);
        sb.append(", hostName=").append(hostName);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", linkMan=").append(linkMan);
        sb.append(", status=").append(status);
        sb.append(", others1=").append(others1);
        sb.append(", other2=").append(other2);
        sb.append(", other3=").append(other3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}