package com.chixing.pojo;

import java.io.Serializable;
import java.util.Date;

public class Like implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.like_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer likeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.like_time
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Date likeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.ticket_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table like
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.like_id
     *
     * @return the value of like.like_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.like_id
     *
     * @param likeId the value for like.like_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.like_time
     *
     * @return the value of like.like_time
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Date getLikeTime() {
        return likeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.like_time
     *
     * @param likeTime the value for like.like_time
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setLikeTime(Date likeTime) {
        this.likeTime = likeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.ticket_id
     *
     * @return the value of like.ticket_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.ticket_id
     *
     * @param ticketId the value for like.ticket_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", likeId=").append(likeId);
        sb.append(", likeTime=").append(likeTime);
        sb.append(", ticketId=").append(ticketId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}