package com.chixing.pojo;

import java.io.Serializable;
import java.util.Date;

public class Refund implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.refund_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer refundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.ticket_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.return_submit_tim
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Date returnSubmitTim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.refund_reason
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String refundReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.refund_price
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Float refundPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.refund_status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table refund
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.refund_id
     *
     * @return the value of refund.refund_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.refund_id
     *
     * @param refundId the value for refund.refund_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setRefundId(Integer refundId) {
        this.refundId = refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.ticket_id
     *
     * @return the value of refund.ticket_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.ticket_id
     *
     * @param ticketId the value for refund.ticket_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.return_submit_tim
     *
     * @return the value of refund.return_submit_tim
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Date getReturnSubmitTim() {
        return returnSubmitTim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.return_submit_tim
     *
     * @param returnSubmitTim the value for refund.return_submit_tim
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setReturnSubmitTim(Date returnSubmitTim) {
        this.returnSubmitTim = returnSubmitTim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.refund_reason
     *
     * @return the value of refund.refund_reason
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getRefundReason() {
        return refundReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.refund_reason
     *
     * @param refundReason the value for refund.refund_reason
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setRefundReason(String refundReason) {
        this.refundReason = refundReason == null ? null : refundReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.refund_price
     *
     * @return the value of refund.refund_price
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Float getRefundPrice() {
        return refundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.refund_price
     *
     * @param refundPrice the value for refund.refund_price
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setRefundPrice(Float refundPrice) {
        this.refundPrice = refundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.refund_status
     *
     * @return the value of refund.refund_status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.refund_status
     *
     * @param refundStatus the value for refund.refund_status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.other1
     *
     * @return the value of refund.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.other1
     *
     * @param other1 the value for refund.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.other2
     *
     * @return the value of refund.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.other2
     *
     * @param other2 the value for refund.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", refundId=").append(refundId);
        sb.append(", ticketId=").append(ticketId);
        sb.append(", returnSubmitTim=").append(returnSubmitTim);
        sb.append(", refundReason=").append(refundReason);
        sb.append(", refundPrice=").append(refundPrice);
        sb.append(", refundStatus=").append(refundStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}