package com.chixing.pojo;

import java.io.Serializable;

public class Seat implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.seat_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer seatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.seat_number
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String seatNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.venues_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer venuesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.is_choose
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer isChoose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seat
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.seat_id
     *
     * @return the value of seat.seat_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.seat_id
     *
     * @param seatId the value for seat.seat_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.seat_number
     *
     * @return the value of seat.seat_number
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getSeatNumber() {
        return seatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.seat_number
     *
     * @param seatNumber the value for seat.seat_number
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setSeatNumber(String seatNumber) {
        this.seatNumber = seatNumber == null ? null : seatNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.venues_id
     *
     * @return the value of seat.venues_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getVenuesId() {
        return venuesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.venues_id
     *
     * @param venuesId the value for seat.venues_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setVenuesId(Integer venuesId) {
        this.venuesId = venuesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.is_choose
     *
     * @return the value of seat.is_choose
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getIsChoose() {
        return isChoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.is_choose
     *
     * @param isChoose the value for seat.is_choose
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setIsChoose(Integer isChoose) {
        this.isChoose = isChoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.status
     *
     * @return the value of seat.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.status
     *
     * @param status the value for seat.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.other1
     *
     * @return the value of seat.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.other1
     *
     * @param other1 the value for seat.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.other2
     *
     * @return the value of seat.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.other2
     *
     * @param other2 the value for seat.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seatId=").append(seatId);
        sb.append(", seatNumber=").append(seatNumber);
        sb.append(", venuesId=").append(venuesId);
        sb.append(", isChoose=").append(isChoose);
        sb.append(", status=").append(status);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}