package com.chixing.pojo;

import java.io.Serializable;

public class TicketsPicture implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets_picture.picture_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer pictureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets_picture.tickets_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer ticketsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets_picture.link
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets_picture.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets_picture.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets_picture.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickets_picture.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets_picture.picture_id
     *
     * @return the value of tickets_picture.picture_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets_picture.picture_id
     *
     * @param pictureId the value for tickets_picture.picture_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setPictureId(Integer pictureId) {
        this.pictureId = pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets_picture.tickets_id
     *
     * @return the value of tickets_picture.tickets_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getTicketsId() {
        return ticketsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets_picture.tickets_id
     *
     * @param ticketsId the value for tickets_picture.tickets_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setTicketsId(Integer ticketsId) {
        this.ticketsId = ticketsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets_picture.link
     *
     * @return the value of tickets_picture.link
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets_picture.link
     *
     * @param link the value for tickets_picture.link
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets_picture.status
     *
     * @return the value of tickets_picture.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets_picture.status
     *
     * @param status the value for tickets_picture.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets_picture.other1
     *
     * @return the value of tickets_picture.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets_picture.other1
     *
     * @param other1 the value for tickets_picture.other1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets_picture.other2
     *
     * @return the value of tickets_picture.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets_picture.other2
     *
     * @param other2 the value for tickets_picture.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickets_picture.other3
     *
     * @return the value of tickets_picture.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther3() {
        return other3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickets_picture.other3
     *
     * @param other3 the value for tickets_picture.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther3(String other3) {
        this.other3 = other3 == null ? null : other3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tickets_picture
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pictureId=").append(pictureId);
        sb.append(", ticketsId=").append(ticketsId);
        sb.append(", link=").append(link);
        sb.append(", status=").append(status);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", other3=").append(other3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}