package com.chixing.pojo;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_true_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String userTrueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_telno
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Long userTelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_sex
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_birth
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Date userBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_coi
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Long userCoi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_register_time
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Date userRegisterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_email
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_image
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String userImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_true_name
     *
     * @return the value of user.user_true_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getUserTrueName() {
        return userTrueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_true_name
     *
     * @param userTrueName the value for user.user_true_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setUserTrueName(String userTrueName) {
        this.userTrueName = userTrueName == null ? null : userTrueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_telno
     *
     * @return the value of user.user_telno
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Long getUserTelno() {
        return userTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_telno
     *
     * @param userTelno the value for user.user_telno
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setUserTelno(Long userTelno) {
        this.userTelno = userTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_sex
     *
     * @return the value of user.user_sex
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_sex
     *
     * @param userSex the value for user.user_sex
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_birth
     *
     * @return the value of user.user_birth
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Date getUserBirth() {
        return userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_birth
     *
     * @param userBirth the value for user.user_birth
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setUserBirth(Date userBirth) {
        this.userBirth = userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_coi
     *
     * @return the value of user.user_coi
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Long getUserCoi() {
        return userCoi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_coi
     *
     * @param userCoi the value for user.user_coi
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setUserCoi(Long userCoi) {
        this.userCoi = userCoi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_register_time
     *
     * @return the value of user.user_register_time
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Date getUserRegisterTime() {
        return userRegisterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_register_time
     *
     * @param userRegisterTime the value for user.user_register_time
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setUserRegisterTime(Date userRegisterTime) {
        this.userRegisterTime = userRegisterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_email
     *
     * @return the value of user.user_email
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_email
     *
     * @param userEmail the value for user.user_email
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_image
     *
     * @return the value of user.user_image
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getUserImage() {
        return userImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_image
     *
     * @param userImage the value for user.user_image
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setUserImage(String userImage) {
        this.userImage = userImage == null ? null : userImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.other2
     *
     * @return the value of user.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.other2
     *
     * @param other2 the value for user.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", userTrueName=").append(userTrueName);
        sb.append(", userTelno=").append(userTelno);
        sb.append(", userSex=").append(userSex);
        sb.append(", userBirth=").append(userBirth);
        sb.append(", userCoi=").append(userCoi);
        sb.append(", userRegisterTime=").append(userRegisterTime);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", userImage=").append(userImage);
        sb.append(", status=").append(status);
        sb.append(", password=").append(password);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}