package com.chixing.pojo;

import java.io.Serializable;

public class Venues implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venues_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer venuesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.host_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer hostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venues_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String venuesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.venues_address
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String venuesAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.others1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String others1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column venues.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table venues
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venues_id
     *
     * @return the value of venues.venues_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getVenuesId() {
        return venuesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venues_id
     *
     * @param venuesId the value for venues.venues_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setVenuesId(Integer venuesId) {
        this.venuesId = venuesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.host_id
     *
     * @return the value of venues.host_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.host_id
     *
     * @param hostId the value for venues.host_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setHostId(Integer hostId) {
        this.hostId = hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venues_name
     *
     * @return the value of venues.venues_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getVenuesName() {
        return venuesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venues_name
     *
     * @param venuesName the value for venues.venues_name
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setVenuesName(String venuesName) {
        this.venuesName = venuesName == null ? null : venuesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.venues_address
     *
     * @return the value of venues.venues_address
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getVenuesAddress() {
        return venuesAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.venues_address
     *
     * @param venuesAddress the value for venues.venues_address
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setVenuesAddress(String venuesAddress) {
        this.venuesAddress = venuesAddress == null ? null : venuesAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.status
     *
     * @return the value of venues.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.status
     *
     * @param status the value for venues.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.others1
     *
     * @return the value of venues.others1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOthers1() {
        return others1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.others1
     *
     * @param others1 the value for venues.others1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOthers1(String others1) {
        this.others1 = others1 == null ? null : others1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.other2
     *
     * @return the value of venues.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.other2
     *
     * @param other2 the value for venues.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column venues.other3
     *
     * @return the value of venues.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther3() {
        return other3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column venues.other3
     *
     * @param other3 the value for venues.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther3(String other3) {
        this.other3 = other3 == null ? null : other3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table venues
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", venuesId=").append(venuesId);
        sb.append(", hostId=").append(hostId);
        sb.append(", venuesName=").append(venuesName);
        sb.append(", venuesAddress=").append(venuesAddress);
        sb.append(", status=").append(status);
        sb.append(", others1=").append(others1);
        sb.append(", other2=").append(other2);
        sb.append(", other3=").append(other3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}