package com.chixing.pojo;

import java.io.Serializable;

public class Warehouse implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouse_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.tickets_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer ticketsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.num1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer num1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.num2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer num2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.num3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer num3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.others1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String others1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private String other3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warehouse
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouse_id
     *
     * @return the value of warehouse.warehouse_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouse_id
     *
     * @param warehouseId the value for warehouse.warehouse_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.tickets_id
     *
     * @return the value of warehouse.tickets_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getTicketsId() {
        return ticketsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.tickets_id
     *
     * @param ticketsId the value for warehouse.tickets_id
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setTicketsId(Integer ticketsId) {
        this.ticketsId = ticketsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.num1
     *
     * @return the value of warehouse.num1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getNum1() {
        return num1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.num1
     *
     * @param num1 the value for warehouse.num1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setNum1(Integer num1) {
        this.num1 = num1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.num2
     *
     * @return the value of warehouse.num2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getNum2() {
        return num2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.num2
     *
     * @param num2 the value for warehouse.num2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setNum2(Integer num2) {
        this.num2 = num2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.num3
     *
     * @return the value of warehouse.num3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getNum3() {
        return num3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.num3
     *
     * @param num3 the value for warehouse.num3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setNum3(Integer num3) {
        this.num3 = num3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.status
     *
     * @return the value of warehouse.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.status
     *
     * @param status the value for warehouse.status
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.others1
     *
     * @return the value of warehouse.others1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOthers1() {
        return others1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.others1
     *
     * @param others1 the value for warehouse.others1
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOthers1(String others1) {
        this.others1 = others1 == null ? null : others1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.other2
     *
     * @return the value of warehouse.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.other2
     *
     * @param other2 the value for warehouse.other2
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.other3
     *
     * @return the value of warehouse.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public String getOther3() {
        return other3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.other3
     *
     * @param other3 the value for warehouse.other3
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    public void setOther3(String other3) {
        this.other3 = other3 == null ? null : other3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Wed Oct 14 20:25:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", warehouseId=").append(warehouseId);
        sb.append(", ticketsId=").append(ticketsId);
        sb.append(", num1=").append(num1);
        sb.append(", num2=").append(num2);
        sb.append(", num3=").append(num3);
        sb.append(", status=").append(status);
        sb.append(", others1=").append(others1);
        sb.append(", other2=").append(other2);
        sb.append(", other3=").append(other3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}